######################################################################################################
#                                              metadata                                              #
######################################################################################################
[project]
name = "q6taaj04do99vgf9cog0gurq6"
version = "0.0.0"

requires-python = ">= 3.11"
dependencies = ["copier>=9.14.3,<10"]

authors = [{name = "Jevan Goh", email = "javerngoh@gmail.com"}]

######################################################################################################
#                                                pixi                                                #
######################################################################################################
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64"]

[tool.pixi.target.linux-aarch64.activation]
env = { LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:$CONDA_PREFIX/lib" }

# ==================================== defaults ====================================
[tool.pixi.dependencies]
git = ">=2.54.0,<3"
gh = ">=2.83.2,<3"

[tool.pixi.tasks.generate]
args = ["project_id"]
cmd = "copier copy --data project_id={{ project_id }} ./q6taaj04do99vgf9cog0gurq6 ./{{ project_id }}"


[tool.pixi.tasks.git_init]
args = ["project_id"]
cmd = "git -C ./{{ project_id }} init -b main"

[tool.pixi.tasks.repo_setup]
args = ["project_id"]
cmd = "cd ./{{ project_id }} && pixi run -e dev setup"

[tool.pixi.tasks.repo_regenerate_stubs]
args = ["project_id"]
cmd = "cd ./{{ project_id }} && pixi run -e dev generate_stubs || true"

[tool.pixi.tasks.repo_pre_commit]
args = ["project_id"]
cmd = "cd ./{{ project_id }} && pixi run -e dev prek run --all-files || true"

[tool.pixi.tasks.git_add]
args = ["project_id"]
cmd = "git -C ./{{ project_id }} add ."

[tool.pixi.tasks.check_drift]
args = ["project_id"]
cmd = "git -C ./{{ project_id }} diff --exit-code"

[tool.pixi.tasks.git_initial_commit]
args = ["project_id"]
cmd = "git -C ./{{ project_id }} commit -m 'Initial commit'"

[tool.pixi.tasks.git_initial_tag]
args = ["project_id"]
cmd = "git -C ./{{ project_id }} tag -a v0.0.0 -m 'release version 0.0.0'"

[tool.pixi.tasks.create_github_repo]
args = ["project_id"]
cmd = "gh repo create {{ project_id }} --public --source=./{{ project_id }} --remote=origin --push"

[tool.pixi.tasks.sleep]
cmd = "sleep 5"

[tool.pixi.tasks.delete_repo_labels]
args = ["project_id"]
cmd = """
    gh label delete 'bug' --repo https://github.com/jevangoh/{{ project_id }} --yes
&&
    gh label delete 'documentation' --repo https://github.com/jevangoh/{{ project_id }} --yes
&&
    gh label delete 'duplicate' --repo https://github.com/jevangoh/{{ project_id }} --yes
&&
    gh label delete 'good first issue' --repo https://github.com/jevangoh/{{ project_id }} --yes
&&
    gh label delete 'help wanted' --repo https://github.com/jevangoh/{{ project_id }} --yes
&&
    gh label delete 'invalid' --repo https://github.com/jevangoh/{{ project_id }} --yes
&&
    gh label delete 'question' --repo https://github.com/jevangoh/{{ project_id }} --yes                
&&
    gh label delete 'wontfix' --repo https://github.com/jevangoh/{{ project_id }} --yes   
&&
    gh label delete 'enhancement' --repo https://github.com/jevangoh/{{ project_id }} --yes    
"""

[tool.pixi.tasks.add_github_labels]
args = ["project_id"]
cmd = """
    gh label create "type: bug" --color "d73a4a" --description "Unexpected outcome." --repo jevangoh/{{ project_id }}
&&
    gh label create "type: suggestion" --color "ffa5a5" --description "Propose improvements or new ideas." --repo jevangoh/{{ project_id }}
&&
    gh label create "scope: source_code" --color "0075ca" --description "The actual source code." --repo jevangoh/{{ project_id }}
&&
    gh label create "scope: docs" --color "a2eeef" --description "Documentation(README, contributing, license, readthedocs, etc)." --repo jevangoh/{{ project_id }}
&&
    gh label create "scope: workflow" --color "5319e7" --description "Continuous Integration (CI) related." --repo jevangoh/{{ project_id }}
"""

[tool.pixi.tasks.init]
args = ["project_id"]
depends-on = [
    {task = "generate", args = ["{{ project_id }}"]},
    {task = "git_init", args = ["{{ project_id }}"]},
    {task = "git_add", args = ["{{ project_id }}"]},
    {task = "repo_setup", args = ["{{ project_id }}"]},
    {task = "repo_regenerate_stubs", args = ["{{ project_id }}"]},
    {task = "git_add", args = ["{{ project_id }}"]},
    {task = "repo_pre_commit", args = ["{{ project_id }}"]},
    {task = "git_add", args = ["{{ project_id }}"]},
    {task = "git_initial_commit", args = ["{{ project_id }}"]},
    {task = "git_initial_tag", args = ["{{ project_id }}"]},
    {task = "create_github_repo", args = ["{{ project_id }}"]},
    {task = "delete_repo_labels", args = ["{{ project_id }}"]},
    {task = "add_github_labels", args = ["{{ project_id }}"]}
]

# ==================================== environments ====================================
# ----------------------------- dev -----------------------------
[tool.pixi.environments.dev]
features = ["docs", "dev"]
solve-group = "default"

# ==================================== features ====================================
# ----------------------------- dev -----------------------------
[tool.pixi.feature.dev.dependencies]
prek = ">=0.2.30,<0.3"
nodejs = ">=24,<25.3"
prettier = ">=3.8.3"

[tool.pixi.feature.dev.tasks]
setup = "prek install"

lint_documents = "prettier --check --ignore-unknown"
format_documents = "prettier --write --ignore-unknown"
lint_all_documents = "prettier --check . --ignore-unknown"
format_all_documents = "prettier --write . --ignore-unknown"

# ----------------------------- docs -----------------------------
[tool.pixi.feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.7.6,<10"
pymdown-extensions = ">=10.20,<11"

[tool.pixi.feature.docs.tasks]
build_docs = "mkdocs build --config-file mkdocs.yaml"

