version: 2

mkdocs:
  configuration: mkdocs.yaml

build:
  os: ubuntu-22.04
  tools:
    python: latest
  jobs:
    build:
      html:
        - curl -fsSL https://pixi.sh/install.sh | bash
        - export PATH="$HOME/.pixi/bin:$PATH" && pixi install -e dev
        - export PATH="$HOME/.pixi/bin:$PATH" && pixi run -e dev zensical build --config-file zensical.toml
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
